server:
  port: 8001


spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingSphere-config.yml
  data:
    redis:
      host: 192.168.70.128
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.70.128:8848


rocketmq:
  name-server: 192.168.70.128:9876
  producer:
    group: short-link_project_common-message-execute-pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
short-link:
  stats:
    locale:
      amap-key: 7d45420859975512ad10090967c84cfd
  domain: uri.link:8001